import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { mintCard } from '../stacksFoundation/mint_card'
import { authenticate, userSession } from '../stacksFoundation/connectWallet'
export let prompt:string=""
export let UrL:string=""
export default function Home() {
  const [value, setValue] = useState('');
  const [imageUrl, setImageUrl] = useState('')
  const url = `https://lexica.art/api/v1/search?q=${value}`

  const buttonClick = async () => {
    let data = await fetch(`https://lexica.art/api/v1/search?q=${value}`)
    let parseData = await data.json()
    setImageUrl(parseData.images[1].src)
    prompt=value;
    UrL=imageUrl;
    
    // fetch(imageUrl).then(async response => {
      
      
    //   const contentType = response.headers.get('content-type')
    //   const blob = await response.blob()
    //   const file = new File([blob], '1.jpeg', { type: blob.type })
    //   console.log(file)
    //   // access file here
    // })
    console.log(imageUrl)
  }
  const checkloggedIn = () => {
        
    userSession.isUserSignedIn() ? mintCard()
        : authenticate()
    prompt=value;
    UrL=imageUrl;
}

  return (
    <section>

      <div className={styles.container}>
        <Head>
          <title>Text To Image</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='bg-black-200	border-red-600 border-4	rounded-3xl	 m-8'>

          <h1 className='ml-4 mt-4 font-extrabold text-transparent text-6xl bg-clip-text mb-4 bg-gradient-to-r from-purple-400 to-pink-600' > Generate Image and make it your own </h1>
          <div className='m-4 flex'>
            <input type="text" value={value} onChange={e => { setValue(e.currentTarget.value); }} className='py-2 w-96 h-12 mr-8 bg-slate-700 placeholder:text-slate-400 rounded-lg flex-auto' placeholder="Search for anything..." ></input>
            <button onClick={buttonClick} className='bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500	py-2 rounded-lg px-24	h-12 flex-1/2'>Generate</button>
            <div className='m-4 flex-row-reverse '>
              <img className='h-96 w-96 border-4 rounded-3xl'
                src={`${imageUrl}`}
                alt="Your generated image will displayed here.!"
              />
            </div>
          </div>
          <button onClick={checkloggedIn} className='mb-8 ml-4 bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500	 rounded-lg px-24	h-12'>Mint Image</button>
        </div>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>

    </section>
  )
}

