import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function HoMe() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Text To Image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-black-200	border-red-600 border-4	rounded-3xl	 m-8'>
        
        <h1 className='ml-4 mt-4 font-extrabold text-transparent text-6xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600' > Generate Image and make it your own </h1>
        <div className='flex m-4'>
        <input type="text" className='py-2 w-96 h-12 mr-8 bg-slate-700 placeholder:text-slate-400 rounded-lg flex-auto' placeholder="Search for anything..." ></input>
        <button type="submit" className='bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500	py-2 rounded-lg px-24	h-12 flex-none'>Search</button>
        <div className='m-4 flex'>
          <img className='h-96 w-96'
            src="https://thumbs.dreamstime.com/b/horse-herd-run-desert-sand-storm-against-dramatic-sky-60327349.jpg"
            alt="example"
          />
        </div>
        </div>
        <button type="submit" className='mb-8 left-0 bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500	 rounded-lg px-24	h-12'>Mint Image</button>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
